In [3]:
import numpy as np
A = np.random.randint(-10, 11, size=(5, 2))
x = np.random.randint(-10, 11, size=(2, 1))
print("Matrix A (5x2):\n", A)
print("\nVector x (2x1):\n",)

# 5x5 Diagonal matrix with values 1,2,3,4,5
B = np.diag([1, 2, 3, 4, 5])
print("\nMatrix B (5x5 diagonal):\n", B)


# Compute Ax and BA

Ax = np.dot(A, x)
BA = np.dot(B, A)

print("\nAx (result of A * x):\n", Ax)
print("\nBA (result of B * A):\n", BA)


Matrix A (5x2):
 [[ -8   7]
 [  6  -5]
 [-10   9]
 [ -4   2]
 [ -4   8]]

Vector x (2x1):


Matrix B (5x5 diagonal):
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Ax (result of A * x):
 [[ 7]
 [-5]
 [ 9]
 [ 2]
 [ 8]]

BA (result of B * A):
 [[ -8   7]
 [ 12 -10]
 [-30  27]
 [-16   8]
 [-20  40]]


In [4]:
import mglearn 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
lr = LinearRegression().fit(X_train, y_train)
print("Training set score: {:.2f}".format(lr.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lr.score(X_test, y_test)))
from sklearn.linear_model import Lasso
lasso = Lasso().fit(X_train, y_train)
print("Training set score: {:.2f}".format(lasso.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lasso.score(X_test, y_test)))
print("Number of features used: {}".format(np.sum(lasso.coef_ != 0)))


Training set score: 0.95
Test set score: 0.61
Training set score: 0.29
Test set score: 0.21
Number of features used: 4


c:\Users\Admin\anaconda3\envs\info6105\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hous